[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "decktor"
version = "0.1.0"
authors = [
    { name = "Mauro Comi" },
]
description = "A simple tool to fix Anki cards using an LLM."
readme = "README.md"
requires-python = ">=3.10"
license = { file = "LICENSE" }
# Your project's dependencies go here
dependencies = [
    "streamlit",
]

[project.scripts]
decktor = "decktor.app:run"

[tool.setuptools]
package-dir = { "" = "src" }
